[package]
name = "oxide"
version = "0.1.0"
authors = ["Rubens Minoru Andako Bueno <rubensmabueno@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"